pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'

steps:

- task: VSBuild@1
  inputs:
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/restore'

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration) --no-build'