pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    version: 6.0.x

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration) --no-build'